swagger: '2.0'
info:
  description: "Essa é  a API disponível para o e-Commerce Compra Fácil desenvolvida pelo Grupo 8."
  version: "1.0.0"
  title: "Compra Fácil API"
  termsOfService: "http://comprefacil.swagger.io/termosDeUso"
  contact:
    email: "equipe08@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "amazonia.swagger.io"
basePath: "/v1"
tags:
  - name: "produtos"
    description: "Operacões disponíveis para busca e gerenciamento de produtos disponibilizados para venda no market place"
  - name: "promocoes"
    description: "Operacões disponíveis para busca e gerenciamento de promoções disponibilizados para venda no market place"
  - name: "lojistas"
    description: "Operacões disponíveis para busca e gerenciamento de lojistas disponibilizados para venda no market place"
  - name: "categorias"
    description: "Recurso para obter as categorias do e-commerce"
  - name: "maisvendidos"
    description: "Operacões disponíveis para busca de produtos mais vendidos"
schemes:
  - https
  - http
paths:
  /produtos:
    post:
      tags:
        - produtos
      summary: Adiciona novo produto
      description: ''
      operationId: addProd
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Objeto com as informações do produto que serão adicionados ao market
            place
          required: true
          schema:
            $ref: '#/definitions/Produto'
      responses:
        '405':
          description: Entrada Invalida
        '505':
          description: Erro interno
      security:
        - comprefacil_auth_fornecedor:
            - 'write:produtos'
            - 'read:produtos'
    put:
      tags:
        - produtos
      summary: Atualiza dados de um produto cadastrado
      description: ''
      operationId: updateProd
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Produto precisa estar cadastrado previamente
          required: true
          schema:
            $ref: '#/definitions/Produto'
      responses:
        '400':
          description: Identificador não válido
        '404':
          description: Produto não encontrado
        '405':
          description: Informações inválidas
      security:
        - comprefacil_auth_fornecedor:
            - 'write:produtos'
            - 'read:produtos'
            
  /produtos/status:
    get:
      tags:
        - produtos
      summary: Encontre os produtos de acordo com seu status
      description: Status multiplos podem ser utilizados (Devem se separados por vírgula).
      operationId: findProductsByStatus
      produces:
        - application/xml
        - application/json
      parameters:
        - name: status
          in: query
          description: Status que serão utilizados como filtro.
          required: true
          type: array
          items:
            type: string
            enum:
              - disponivel
              - nao disponivel
            default: disponivel
          collectionFormat: multi
      responses:
        '200':
          description: Operação finalizada
          schema:
            type: array
            items:
              $ref: '#/definitions/Produto'
        '400':
          description: Ao menos um dos status informado é inválido
      security:
        - comprefacil_auth_fornecedor:
            - 'write:produtos'
            - 'read:produtos'
  /produtos/findTags:
    get:
      tags:
        - produtos
      summary: Encontre os produtos de acordo com as tags vinculadas
      description: Tags multiplos podem ser utilizados (Devem se separados por vírgula).
      operationId: findProductsByTags
      produces:
        - application/xml
        - application/json
      parameters:
        - name: tags
          in: query
          description: Tags que serão utilizados como filtro
          required: true
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        '200':
          description: Operação finalizada
          schema:
            type: array
            items:
              $ref: '#/definitions/Produto'
        '400':
          description: Ao menos uma das tags informado é inválido
      security:
        - comprefacil_auth_fornecedor:
            - 'write:produtos'
            - 'read:produtos'
        
  /produtos/{produtoId}:
    get:
      tags:
        - produtos
      summary: Encontra produto pelo ID
      description: Retorna as informações do produto com o id.
      operationId: getProductById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: produtoId
          in: path
          description: ID do produto a ser encontrado
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Operação finalizada com sucesso
          schema:
            $ref: '#/definitions/Produto'
        '400':
          description: ID informado é inválido
        '404':
          description: Produto não encontrado
      security:
        - api_key: []
    post:
      tags:
        - produtos
      summary: Atualiza dados do produto informado
      description: ''
      operationId: updateProductWithForm
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/xml
        - application/json
      parameters:
        - name: produtoId
          in: path
          description: ID do produto a ser atualizado
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: >-
            Objeto com as informações do produto que serão atualizado no
            marketplace
          required: true
          schema:
            $ref: '#/definitions/Produto'
      responses:
        '200':
          description: Operação finalizada com sucesso
          schema:
            $ref: '#/definitions/Produto'
        '400':
          description: ID informado é inválido
        '404':
          description: Produto não encontrado
        '405':
          description: Informações inválidas
      security:
        - comprefacil_auth_fornecedor:
            - 'write:produtos'
            - 'read:produtos'
    delete:
      tags:
        - produtos
      summary: Remove o produto vinculado ao ID
      description: ''
      operationId: deleteProduct
      produces:
        - application/xml
        - application/json
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: produtoId
          in: path
          description: Produto a ser deletado
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Operação finalizada com sucesso
        '400':
          description: ID informado é inválido
        '404':
          description: Produto não encontrado
        '405':
          description: Informações inválidas
      security:
        - comprefacil_auth_fornecedor:
            - 'write:produtos'
            - 'read:produtos'
  /produtos/{produtoId}/uploadimage:
    post:
      tags:
        - produtos
      summary: Faz o upload de uma imagem para o produto com o ID vinculado
      description: ''
      operationId: uploadFile
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: produtoId
          in: path
          description: ID do produto onde a imagem será incluída
          required: true
          type: integer
          format: int64
        - name: additionalMetadata
          in: formData
          description: Informações que serão verificadas pelo servidor
          required: false
          type: string
        - name: file
          in: formData
          description: Arquivo da imagem que será incluída no produto
          required: false
          type: file
      responses:
        '200':
          description: Operação finalizada com sucesso
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: ID informado é inválido
        '404':
          description: Produto não encontrado
      security:
        - comprefacil_auth_fornecedor:
            - 'write:produtos'
            - 'read:produtos'
          
  /produtos/promocoes:
    get:
      tags:
        - promocoes
      summary: Lista os produtos em promoção no e-commerce
      description: A lista ira conter todos os produtos em promoção
      responses:
        200:
          description: Operação finalizada
          schema:
            type: array
            items:
              $ref: '#/definitions/Produto'
        403:
          description: "Requisição Inválida"
        405:
          description: "Operação não permitida"
    
  /categorias:
    get:
      tags:
        - "categorias"
      summary: "Lista as categorias existentes no e-commerce"
      description: ""
      operationId: "listCategorias"
      produces:
        - "application/json"
      parameters:
        - name: "_offset"
          in: header
          description: "Parâmetro que determina a posição inical da consulta"
          required: false
          type: "integer"
          format: "int64"
        - name: "_limit"
          in: header
          description: "Parâmetro que determina a quantidade de itens que serão retornados"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "Indica que o processamento foi bem sucedido"
          schema: 
              type: "array"
              items: 
                $ref: "#/definitions/Categoria"
        403:
          description: "Requisição Inválida"
        405:
          description: "Operação não permitida"
      security:
        - comprefacil_auth_fornecedor:
            - "write:produtos"
            - "read:produtos"
            
  /categorias/{categoriaId}/produtos:
    get:
      tags:
        - categorias
      summary: Lista produtos de determinada Categoria
      description: Retorna as informações do produto de determinada Categoria com o id.
      operationId: getProductByCategory
      produces:
        - application/xml
        - application/json
      parameters:
        - name: "_offset"
          in: header
          description: "Parâmetro que determina a posição inical da consulta"
          required: true
          type: "integer"
          format: "int64"
        - name: "_limit"
          in: header
          description: "Parâmetro que determina a quantidade de itens que serão retornados"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "Indica que o processamento foi bem sucedido"
          schema: 
              type: "array"
              items: 
                $ref: "#/definitions/Produto"
        403:
          description: "Requisição Inválida"
        400:
          description: "A categoria fornecida é inválida"
        405:
          description: "Operação não permitida"
      security:
        - comprefacil_auth_fornecedor:
            - 'write:produtos'
            - 'read:produtos'
            
  /maisvendidos:
    get:
      tags:
        - "maisvendidos"
      summary: "Lista os produtos mais vendidos do e-commerce"
      description: ""
      operationId: "listMaisVendidos"
      produces:
        - "application/json"
      parameters:
        - name: "_offset"
          in: header
          description: "Parâmetro que determina a posição inical da consulta"
          required: true
          type: "integer"
          format: "int64"
        - name: "_limit"
          in: header
          description: "Parâmetro que determina a quantidade de itens que serão retornados"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "Indica que o processamento foi bem sucedido"
          schema: 
              type: "array"
              items: 
                $ref: "#/definitions/Produto"
        403:
          description: "Requisição Inválida"
        405:
          description: "Operação não permitida"
      security:
        - comprefacil_auth_fornecedor:
            - "write:produtos"
            - "read:produtos"   
  /maisvendidos/{categoriaid}:
    get:
      tags:
      - "maisvendidos"
      summary: "Lista os produtos mais vendidos de determinada categoria"
      description: ""
      operationId: "listMaisVendidosByCategoria"
      produces:
      - "application/json"
      parameters:
        - name: "categoriaid"
          in: "path"
          description: "Parâmetro que determina a posição inical da consulta"
          required: true
          type: "integer"
          format: "int64"
        - name: "_offset"
          in: header
          description: "Parâmetro que determina a posição inical da consulta"
          required: true
          type: "integer"
          format: "int64"
        - name: "_limit"
          in: header
          description: "Parâmetro que determina a quantidade de itens que serão retornados"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "Indica que o processamento foi bem sucedido"
          schema: 
              type: "array"
              items: 
                $ref: "#/definitions/Produto"
        403:
          description: "Requisição Inválida"
        400:
          description: "A categoria fornecida é inválida"
        405:
          description: "Operação não permitida"
      security:
        - comprefacil_auth_fornecedor:
            - 'write:produtos'
            - 'read:produtos'    
 
securityDefinitions:
  comprefacil_auth_fornecedor:
    type: oauth2
    authorizationUrl: "http://comprefacil.swagger.io/oauth/dialogFornecedor"
    flow: "implicit"
    scopes:
      'write:produtos': "Modifica ou cria novos produtos vinculados a sua conta"
      'read:produtos': "Lê produtos vinculados a sua conta"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

definitions:
  Produto:
    type: "object"
    required:
      - "name"
      - "photoUrls"
      - "preco"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "Identificação do produto na e-Commerce compra facil"
      name:
        type: "string"
        example: "Computador Dell"
        description: "Descrição do produto"
      sku:
        type: "string"
        example: "90NB0KZ1-M00220"
        description: "SKU do produto"
      preco:
        type: "number"
        format: "float"
        description: "preço de venda"
        example: 9999.
      estoque:
        type: "number"
        format: "float"
        description: "quantidade em estoque"
        example: 9999.
      peso:
        type: "number"
        format: "float"
        description: "peso em kilogramas (Kg) do produto"
        example: 9999.
      altura:
        type: "number"
        format: "float"
        description: "altura em milimetros (mm) do produto"
        example: 9999.  
      largura:
        type: "number"
        format: "float"
        description: "largura em milimetros (mm) do produto"
        example: 9999.
      comprimento:
        type: "number"
        format: "float"
        description: "comprimento em milimetros (mm) do produto"
        example: 9999.
      promotional_price:
        type: "number"
        format: "float"
        description: "preço de venda na promoção"
        example: 9999.
      start_promotion:
        type: "string"
        format: "date"
        description: "Data de início da promoção do produto"
        example: "2020-07-21"
      end_promotion:
        type: "string"
        format: "date"
        description: "Data de termino da promoção do produto"
        example: "2020-08-21"  
      categorias:
        type: array
        xml:
          name: categoria
          wrapped: true
        items:
          $ref: '#/definitions/Categoria'
      photoUrls:
        type: array
        xml:
          name: fotoUrl
          wrapped: true
        items:
          type: string
      tags:
        type: array
        xml:
          name: tag
          wrapped: true
        items:
          $ref: '#/definitions/Tag'
      status:
        type: string
        description: Status atual do produto
        enum:
          - disponível
          - não disponivel
    xml:
      name: Produto
  Categoria:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 111
        description: "ID da categoria"
      parentid:
        type: "integer"
        format: "int64"
        example: 20
        description: "ID da categoria pai"
      items:
        type: "integer"
        format: "int64"
        example: 569
        description: "Total de items da categoria"
      name:
        type: "string"
        example: "Computadores"
        description: "Nome da categoria"
      desc:
        type: string
        example: "Notebooks, Desktops, All-In-One"
        description: "Descrição da categoria"

  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Tag
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
